### ISSUE TITLE
Pattern Matching

### ISSUE THREAD

**Issue by igorbonadio** [positron-lang/spec#16]
Lets talk about pattern matching

**Comment by renatocf** [comment]
Marking as opened to #18

**Comment by vinivendra** [comment]
Given what we've discussed about functions so far, what are your ideas for pattern matching?

**Comment by igorbonadio** [comment]
I think we should match only tuples:

``` ruby
let (a, b, c) = ("blah", 1, 2.2) # valid
let (a, b, c) : (String, Int, Float) = ("blah", 1, 2.2) # valid
let (a, _, _) = ("blah", 1, 2.2) # valid. Just a is defined.
let ("blah", b, c) = ("blah", 1, 2.2) # valid. b and c are defined.
let ("wrong", b, c) = ("blah", 1, 2.2) # invalid. 1st argument doesn't match
```

But I think we could define a method that converts an object into a tuple:

``` ruby
class Point
  var a: Int
  var b: Int

  def to_tuple() -> (tuple: (String, Int, Int))
    tuple = ("Point", a, b)
  end
end
```

And then:

``` ruby
var point = Point.new(a: 1, b: 2)
var ("Point", x, y) = point.to_tuple() # x is 1 and y is 2
```

It will be useful in a match/case expression:

``` ruby
match(point) # here, the match statement calls 'to_tuple'
  case ("Point", x, y) => x + y
end
```

A full example:

``` ruby
def receive_package_from_network(net: Network) -> ()
  match(net.read())
    case ("timeout", _) => IO.print(txt: "[Error] timeout")
    case ("ok", pkg)    => IO.print(txt: pkg)
  end
end
```

Another example:

``` ruby
class Boolean
  var value: String

  def to_tuple() -> (tuple: (String))
    tuple = value
  end

  def and(b: Boolean) -> (result: Boolean)
    match(self, b)                               # here, 'match' calls:
      case ("true", "true") => result = "true"   # * self.to_tuple() witch returns (self.value)
      case (_, _)           => result = "false"  # * b.to_tuple() witch returns (b.value)
    end                                          # and both are equal to: self.value and b.value
  end                                            # so, (self, b) is equal to (self.value, b.value)

  def or(b: Boolean) -> (result: Boolean)
    match((self, b))
      case (("false"), ("false")) => result = "false" # here I'm using all the optional parenthesis...
      case (_, _)                 => result = "true"
    end
  end
end
```

**Comment by vinivendra** [comment]
Ok, I like how this looks. Let me see if I got this straight.
- In a **test for equality**, such as a `match`, we test each element for equality. The `match` succeeds only if all individual element's tests succeed.
- In an **assignment**, each element may require an assignment or a test for equality. For instance, if we do

``` scala
let ("foo", a) = (b, c)
```

we first check the first elements, `"foo"` and `b`. Since it's a constant and a variable, we know we have to test for equality: `"foo" == b`. If this test succeeds, we check the second elements, `a` and `c`. Since it's two variables, we can do an assignment: `a = c`. If any of the elements are `_`, that assignment (or that test) is skipped. If any of the tests fail, we ignore that line of code and no assignments are done.

Is this right?

**Comment by vinivendra** [comment]
If this is it, I have a few comments:

I'd switch the `to_tuple` method to just `tuple`. I'd rather avoid methods with two words as much as possible, so as to avoid committing the language to using snake_case or camelCase by default.

I'd also switch the common practices of that method to using a type instead of a string:

``` ruby
def tuple() -> (tuple: (Type, Int, Int))
    tuple = (Point, a, b)
    # or another syntax
    tuple = (Point.type, a, b)
end
```

It makes more sense to me, and think type comparisons might be a lot faster than string comparisons.

**Comment by vinivendra** [comment]
Also, if we're considering all operators are just methods, why not allow any operators in matches?

``` ruby
match ("foo", a, b) # defaults to ==
    case ("bar", c, d)
    #...

match (a, b, c) >= # using the >= operator
    case (d, e, f) # works if a >= d, b >= e and c >= f
    #...

match (a, b, c) or # using the or operator
    case (d, e, f) # works if a or d, b or e and c or f
    #...

match ("foo", b, c) = # using the assignment operator
    case (c, e, f) # if c == "foo", we assign b = e and c = f and the case gets matched
                   # just like normal variable assignments: let ("foo", b, c) = (c, e, f)
    #...
```

What do you think?

**Comment by igorbonadio** [comment]
Yes! You got it.

And I agree, `tupe()` is a better name. And its implementation is up to the user. If you want, you can skip the 1st element of the tuple... But I like you solution. Returning the type is really cleaver.

(We can discuss (in other issue) if we will have `Symbol`s [something like a constant string])

Now, about the use of other operator... Your examples don't  work because we have variables in the `case` statement. But I think I got the idea. 

In functional languages we have something that is called "guards":

``` ruby
let number = 123
match tuple
  case ("foo", a, b) and (a > 42)         => ...
  case ("foo", a, b) and (b < 42)         => ...
  case ("foo", a, b) and (a + b > number) => ...
end
```

What do you think?

**Comment by vinivendra** [comment]
Oh ok, so the variable names we use in the `case` statements are just references to the values in the actual tuple we're using, is that it?

``` ruby
let a = 5
let tuple = ("foo", a)

match tuple
    case ("foo", number) # => number is now a reference to the variable a
        number.increase() # => assuming Integer's have an increase() method, a is now 6
```

**Comment by igorbonadio** [comment]
Yes. It very similar to

``` ruby
try
  ("foo", number) = tuple
  number.increase()
catch
  try
    ("bar", number) = tuple
    number.increase()
  catch
    throws "cant match..."
  end
end
```

**Comment by vinivendra** [comment]
Ok. I like the guards, it's a nice touch. Is that the syntax you propose for them? I'm not sure about it, since it doesn't seem like we're using `and` as a normal operator. For instance, it doesn't make sense to be able to substitute `and`s for `or`s in this case.

Also, is there really an exception thrown if there are no matched patterns?

**Comment by igorbonadio** [comment]
I don't like the syntax too... It was just to illustrate the concept.

In FP languages, `match` throws an exception when there are no matched pattern because it is an expression, so:

``` ruby
result = match tuple
  case (...) => a_result
end
```

Is our `match` an expression?

If it is, we can return `nil` or throw an exception in this case. What do you think?

Ah, and we can have an `otherwise` case:

``` ruby
match tuple
  case (...) => a_result
  otherwise => ...
  # or maybe `else` instead of `otherwise`:
  else => ...
  # or maybe just '_' is sufficient
  case _ => ...
end
```

**Comment by vinivendra** [comment]
On one side, I think `match` should be an expression because we wanted everything to be an expression. On the other side, does it make sense now that we no longer return the last value on a function? I mean, the `a_result` as its own statement seems a little odd if we allow other block expressions to be mixed in as well (and if we don't allow it on function bodies). What do you think?

**Comment by igorbonadio** [comment]
I like the idea of "everything is an expression".

For example:

``` ruby
def area(shape: Shape) -> (result: Float)
  result = match shape
    ("Circle", r) => Math.pi*r*r
    ("Square", a) => a*a
  end
end
```

It is better than:

``` ruby
def area(shape: Shape) -> (result: Float)
  match shape
    ("Circle", r) => result = Math.pi*r*r
    ("Square", a) => result = a*a
  end
end
```

**Comment by vinivendra** [comment]
I have nothing against that, but what if we inserted normal code in the cases? Would we just return the last value, like we initially intended?

``` ruby
def area(shape: Shape) -> (result: Float)
    result = match shape
        ("Circle", r) => Math.pi*r*r
        ("Square", a) => a*a
        ("Triangle", a) =>
            var twiceTheResult = a*a
            someOtherStuff()
            evenMoreStuff()
            twiceTheResult / 2
    end
end
```

We could disallow normal code in these cases, but then those matches wouldn’t be valid as expressions - which breaks our premise.

What do you think?

**Comment by igorbonadio** [comment]
I think we should return the last value

**Comment by vinivendra** [comment]
Ok. I guess if we trust the user is going to write decent code, we can trust that the code won't get too confusing.

I like an `else` clause better than an `otherwise`, but I'd be ok either way. I prefer them over having to do `case _, _, _ ...`, I think they're clearer. In fact, for standardization's sake, I'd disallow a `case` with only `_`s and substitute it for an `else`.

Also, what do you suggest for the guard clauses? Do you think maybe we can put them inside the tuples?

``` ruby
match tuple
    case ("Circle" or "Rectangle", a, b) => a * a
    case (_, a <= 0, _) => 0
    # ...
```

**Comment by igorbonadio** [comment]
Wow! I liked your guards syntax!

And I suggested `otherwise` because `else` is a keyword of `if`... but it can be `else` too. No problem.

And I agree: we should disallow a case with only `_`s.

**Comment by vinivendra** [comment]
I like else because I think of match like a switch, so it makes sense to me. Also, it has four letters, just like "case" :)

This guards syntax does have a problem: it's easy to write "and"s (just put them inside also), but not "or"s. In the above case, it makes sense to return 0 if either a or b is <= 0, but I couldn't think of a way to put that inside the pattern.

Perhaps we can do it like the switch statements, which fall through:

``` ruby
match tuple
    case ("Square" or "Rectangle", a, b) => a*b
    case (a <= 0, _)
    case (_, b<= 0) => 0
```

What do you think?

**Comment by igorbonadio** [comment]
I don't like switch-like statements...

`or` can be used only inside tuple elements (and it seems to work). But there aren't operator between elements... it works like an `and`. I think it's better:

``` ruby
match tuple
  case ("Square" or "Rectangle", a, b) => a*b
  case (n <= 0 or n >= 10, _) => 1
  case (a <= 0, _) => 0
  case (_, b<= 0) => 0
end
```

And users can eliminate duplicates using "extract-method":

``` ruby
match tuple
  case ("Square" or "Rectangle", a, b) => a*b
  case (n <= 0 or n >= 10, _) => 1
  case (a <= 0, _) => do_something_complex()
  case (_, b<= 0) => do_something_complex()
end
```

**Comment by vinivendra** [comment]
Ok, I don't like those switches very much either. Still, I'd rather avoid repetition whenever possible. What about using commas? Or even just spaces, I guess.

``` ruby
match tuple
    case (a <= 0, b), (a, b <= 0) => 0

match tuple
    case (a <= 0, b) (a, b <= 0) => 0
```

I thought about `or`s or `and`s, but I'd like to keep them with only one meaning.

**Comment by igorbonadio** [comment]
I liked the 2nd one. (Or I think that I liked it... I have to think more about it).

But I would write it like:

``` ruby
match tuple
  case (a <= 0, b)
       (a, b <= 0) => 0
end

# or
match tuple
  case (a <= 0, b    )
       (a    , b <= 0) => 0
end
```

**Comment by vinivendra** [comment]
Yeah, that does look a lot better! What do you think?

**Comment by igorbonadio** [comment]
Yes. It seems good.

Can I close this issue?

**Comment by vinivendra** [comment]
Fine by me!

**Comment by igorbonadio** [comment]
So I will close it. 

We can reopen it in the future if necessary.
