### ISSUE TITLE
License

### ISSUE THREAD

**Issue by igorbonadio** [positron-lang/spec#3]
Which license should we use?

**Comment by renatocf** [comment]
Well, the classic licenses are GPL, MIT and Apache. MIT offers wider possibilities for users - including closing the code. Because of this, I think that GPL is better: it really ensures that any code we create remains open - the full sense of free software ("free as in freedom", as would say Stallman, to don't let English speakers confuse it with "free as in beer"). Does it seems reasonable?

**Comment by igorbonadio** [comment]
I agree. But which version of GLP is better?

**Comment by renatocf** [comment]
Hum... As far as I know, GPLv2 and GPLv3 have differences related to uses of software in embedded systems. But I'm not 100% sure. Looking around other "recent" open source projects (as Rust or Neovim), I saw that many of them changed their license after some time - which shows that this is not a consensus and that we have to option of changing in the future. While we don't have code, we can study a little bit more about this topic.

For a general (very high level and simplified) discussion about licenses, we can see:
http://choosealicense.com/

For some basic explanations about GPLv2 vs GPLv3:
http://stackoverflow.com/questions/41460/what-are-the-differences-between-gpl-v2-and-gpl-v3-licenses

**Comment by igorbonadio** [comment]
Ok. So I will close this issue.

We can reopen it in the future.
